function cat_ = build_dpo_catalog()
%% Purpose:
%
%   Packages the completed DPO -> TULIP sheets into the shareable compact
%   catalog costate_catalog_dpo_tulip.mat, via the family-agnostic
%   packager costate_common/build_costate_catalog_family. Run from MATLAB
%   after the catalog run completes (run_dpo_catalog('report') to check).
%
%% Inputs:
%
%   none
%
%% Outputs:
%
%  cat_                     struct                  The catalog, also saved
%                                                   to direct/results/
%                                                   costate_catalog_dpo_tulip.mat
%
%% Revision History:
%  M. Casey                                                   (c) 08/08/2026
%  Copyright Coorbital Inc.
%% ------------------------ Begin Code Sequence ---------------------------

here = fileparts(mfilename('fullpath'));
addpath(fullfile(fileparts(here), 'costate_common'));

spec = struct( ...
  'glob', 'dpo_tau*_Np*.mat', ...
  'name', 'costate_catalog_dpo_tulip', ...
  'description', ['Minimum-time low-thrust DPO->Tulip costate CATALOG: ', ...
    'one phasing-torus sheet per (distant-prograde-orbit period x tulip ', ...
    'petal count), thrust rungs walked 15->0.5 N. COMPACT format: canonical ', ...
    'ND quantities only; derived values reconstructed via .derive. Each ', ...
    'entry z8 = [lambda_r(3); lambda_v(3); lambda_m; tf] is a converged ', ...
    'PMP solution accepted unchanged by pumpkyn.cr3bp.tfMin. NOTE: ', ...
    'sheets(k).tauDRO is a LEGACY field name -- it holds the DPO period ', ...
    '(ND, which is also the getDPO selector); sheets(k).dep_family/', ...
    'dep_params carry the reconstruction recipe.'], ...
  'provenance', ['DPO catalog run (run_dpo_catalog): per sheet, 6x6 ', ...
    'phasing torus anchored cold at 15 N and walked down; three gates per ', ...
    'entry (ms residual, flown arrival, tfMin acceptance). DPO box from ', ...
    'the measured admissibility survey (run_dpo_bounds: tau 0.048-4.695 ', ...
    'ND under the >=500 km periselene / <=100 Mm criteria). Arrival ', ...
    'tulips pm = -1 branch; pm = +1 is the exact z-mirror (CR3BP ', ...
    'symmetry). Casey/Koblick 2026-08.'], ...
  'depReconstruction', ['dpo: getDPO(dep_params.tau)->cont_np->prop ', ...
    '(planar family);  tulip: getTulip(2*pi*(Np-2)/(Np-1), Np, pm)->', ...
    'cont_np->prop;  state at phase f: interp1(t, rv, mod(f,1)*t(end), ', ...
    '''spline'')']);

catDir = fullfile(here, 'direct', 'results', 'catalog');
outMat = fullfile(here, 'direct', 'results', 'costate_catalog_dpo_tulip.mat');
cat_ = build_costate_catalog_family(catDir, outMat, spec);
end
