function lib = build_costate_lib_v2(ladderMat, outMat)
% BUILD_COSTATE_LIB_V2  Package the thrust-ladder results as a shareable library.
%
% Produces costate_lib_dro_tulip_v2: the DRO->tulip minimum-time costate
% library with a THRUST AXIS. Every entry is a converged PMP solution keyed by
% (departure phase, arrival phase, thrust), verified three ways -- multiple-
% shooting residual, end-to-end PMP flight, and acceptance by
% pumpkyn.cr3bp.tfMin. A recipient needs only pumpkyn and this file.
%
% INPUTS:
%   ladderMat - thrust_ladder_12x12.mat from thrust_ladder_library
%   outMat    - output .mat path holding costate_lib_dro_tulip_v2
%
% OUTPUTS:
%   lib - structure:
%         .name .description .provenance .created
%         .constants        (muStar, lStar km, tStar s)
%         .thruster         (Isp s, m0 kg, thrust rungs N)
%         .departure_orbit  'DRO'   + .departure_params (tau = PERIOD in ND)
%         .arrival_orbit    'Tulip' + .arrival_params
%         .entries          [n x 1]: departure/arrival phase (frac, ND, days),
%                           thrust_N, isp_s, m0_kg, lambda0 [7x1], tf_nd,
%                           tf_days, z8 [8x1] (tfMin-ready), ms_residual,
%                           flight_miss_km
%         .grid             has_solution / tf_days / entry_index
%                           [nD x nA x nRung], phase axes, rung axis
%         .usage            worked example
%
% REFERENCES:
%   [1] thrust_ladder_library.m -- how the entries were produced.
%   [2] process/COSTATE_LIBRARY_PIPELINE.md -- the three-step process.

Q = load(ladderMat);
ob = Q.meta;
nD = numel(Q.sD);  nA = numel(Q.sA);  nR = numel(Q.rungs);

lib = struct();
lib.name = 'costate_lib_dro_tulip_v2';
lib.description = ['Minimum-time low-thrust DRO->Tulip transfer costate ', ...
    'library over the (departure phase x arrival phase x THRUST) grid, ', ...
    'CR3BP Earth-Moon. Each entry is a converged PMP solution: z8 = ', ...
    '[lambda_r(3); lambda_v(3); lambda_m; tf] in pumpkyn.cr3bp.tfMin ', ...
    'convention. Verified three ways: multiple-shooting residual ~1e-11, ', ...
    'end-to-end PMP flight arrives at the target, and tfMin accepts the ', ...
    'entry unchanged.'];
lib.created = datestr(now, 'yyyy-mm-dd');
lib.provenance = ['Direct Hermite-Simpson collocation anchored at the HIGH ', ...
    'thrust end (nearly impulsive, sub-revolution, converges cold), then ', ...
    'thrust walked DOWN with each rung warm-started from the one above so ', ...
    'a cell stays on one solution family; per rung: flown verification -> ', ...
    'multiple-shooting refinement (ms_tfmin) -> tfMin acceptance. ', ...
    'Casey/Koblick 2026-08.'];

lib.constants = struct('muStar', ob.muStar, 'lStar_km', ob.lStar, ...
    'tStar_s', ob.tStar, 'nd_time_to_days', ob.tStar/86400);

g0 = 9.80665*ob.tStar^2/(1000*ob.lStar);
lib.thruster = struct('isp_s', ob.ispS, 'm0_kg', ob.m0kg, ...
    'thrust_rungs_N', Q.rungs, ...
    'c_nd', (ob.ispS/ob.tStar)*g0, ...
    'thrust_nd_formula', 'Tmax_nd = (T_N/m0_kg)*tStar^2/(lStar_km*1000)', ...
    'note', ['tfMin args are Tmax_nd and c_nd; each entry carries its own ', ...
             'thrust_N, and Tmax_nd follows from the formula above.']);

lib.departure_orbit = 'DRO';
lib.departure_params = struct('tau', ob.tauDRO, ...
    'tau_is_period', ['getDRO(tau) selects the DRO whose PERIOD = tau (ND); ', ...
        'this library: tau = 1.0 = 4.433 days'], ...
    'period_nd', ob.periodDRO, 'period_days', ob.periodDRO*ob.tStar/86400, ...
    'reconstruction', ['[~,rv0] = pumpkynPie.cr3bp.getDRO(tau); ', ...
        'rv0 = pumpkyn.cr3bp.cont_np(rv0,tau,muStar,1e-12); ', ...
        '[t,rv] = pumpkyn.cr3bp.prop(tau,rv0,muStar); ', ...
        'state at phase f: interp1(t,rv,mod(f,1)*t(end),''spline'')']);

lib.arrival_orbit = 'Tulip';
lib.arrival_params = struct('tau', ob.tauTulip, 'Np', ob.NpTulip, ...
    'pm', ob.pmTulip, ...
    'period_nd', ob.periodTulip, 'period_days', ob.periodTulip*ob.tStar/86400, ...
    'reconstruction', ['[~,rvf] = pumpkyn.cr3bp.getTulip(tau,Np,pm); ', ...
        'rvf = pumpkyn.cr3bp.cont_np(rvf,tau,muStar,1e-12); ', ...
        '[t,rv] = pumpkyn.cr3bp.prop(tau,rvf,muStar); ', ...
        'state at phase f: interp1(t,rv,mod(f,1)*t(end),''spline'')']);

entries = struct([]);
idx = zeros(nD,nA,nR);
n = 0;
for iD = 1:nD
    for iA = 1:nA
        for kr = 1:nR
            if ~Q.OK(iD,iA,kr), continue, end
            n = n + 1;
            z = Q.Z8(:,iD,iA,kr);
            entries(n,1).departure_phase_frac = Q.sD(iD);
            entries(n,1).departure_phase_nd   = Q.sD(iD)*ob.periodDRO;
            entries(n,1).departure_phase_days = Q.sD(iD)*ob.periodDRO*ob.tStar/86400;
            entries(n,1).arrival_phase_frac   = Q.sA(iA);
            entries(n,1).arrival_phase_nd     = Q.sA(iA)*ob.periodTulip;
            entries(n,1).arrival_phase_days   = Q.sA(iA)*ob.periodTulip*ob.tStar/86400;
            entries(n,1).thrust_N             = Q.rungs(kr);
            entries(n,1).isp_s                = ob.ispS;
            entries(n,1).m0_kg                = ob.m0kg;
            entries(n,1).lambda0              = z(1:7);
            entries(n,1).tf_nd                = z(8);
            entries(n,1).tf_days              = z(8)*ob.tStar/86400;
            entries(n,1).z8                   = z;
            entries(n,1).ms_residual          = Q.RES(iD,iA,kr);
            entries(n,1).flight_miss_km       = Q.FLYKM(iD,iA,kr);
            idx(iD,iA,kr) = n;
        end
    end
end
lib.entries = entries;
lib.n_entries = n;

lib.grid = struct( ...
    'departure_phase_frac', Q.sD(:)', ...
    'departure_phase_days', Q.sD(:)'*ob.periodDRO*ob.tStar/86400, ...
    'arrival_phase_frac',   Q.sA(:)', ...
    'arrival_phase_days',   Q.sA(:)'*ob.periodTulip*ob.tStar/86400, ...
    'thrust_N',             Q.rungs(:)', ...
    'has_solution',         Q.OK, ...
    'tf_days',              Q.TF*ob.tStar/86400, ...
    'entry_index',          idx, ...
    'note', ['has_solution(i,j,k): departure phase i, arrival phase j, ', ...
             'thrust rung k. entry_index(i,j,k) is the row of lib.entries ', ...
             '(0 = no solution).']);

lib.usage = sprintf([ ...
    '%% Pick by phases (days) and thrust (N), interpolating t_f between rungs:\n', ...
    'L = load(''costate_lib_dro_tulip_v2.mat'');  lib = L.costate_lib_dro_tulip_v2;\n', ...
    '[tf_days, e] = costate_lib_pick(lib, depDays, arrDays, thrustN);\n', ...
    '%% e.z8 is a tfMin-ready seed at the NEAREST rung; tf_days is linearly\n', ...
    '%% interpolated between the bracketing rungs at that phase pair.\n', ...
    '%% Fly it directly:\n', ...
    'Tnd = (e.thrust_N/lib.thruster.m0_kg)*lib.constants.tStar_s^2/ ...\n', ...
    '      (lib.constants.lStar_km*1000);\n', ...
    '[t,y] = pumpkyn.cr3bp.tfMinProp(e.tf_nd, [rv0(1:6)''; 1; e.lambda0], ...\n', ...
    '        Tnd, lib.thruster.c_nd, lib.constants.muStar);\n', ...
    '%% ...or hand the seed to the single-shooting solver (accepts unchanged):\n', ...
    'z = pumpkyn.cr3bp.tfMin(rv0(1:6), rvf(1:6), e.z8, Tnd, lib.thruster.c_nd, ...\n', ...
    '    lib.constants.muStar);\n']);

costate_lib_dro_tulip_v2 = lib; %#ok<NASGU>
save(outMat, 'costate_lib_dro_tulip_v2');
fprintf('costate_lib_dro_tulip_v2: %d entries (%d phase pairs x up to %d rungs) -> %s\n', ...
    n, nnz(any(Q.OK,3)), nR, outMat);
end
