function A = cartpole_state_jac_gen(in1,u,in3)
%CARTPOLE_STATE_JAC_GEN
%    A = CARTPOLE_STATE_JAC_GEN(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    17-Sep-2026 15:20:39

L = in3(3,:);
g = in3(4,:);
m1 = in3(1,:);
m2 = in3(2,:);
q2 = in1(2,:);
q2d = in1(4,:);
t2 = cos(q2);
t3 = sin(q2);
t4 = m2.^2;
t5 = q2.*2.0;
t6 = q2d.^2;
t7 = t2.^2;
t8 = t2.^3;
t9 = t3.^2;
t10 = t7-1.0;
t11 = m2.*t10;
t12 = -t11;
t13 = m1+t12;
t14 = 1.0./t13.^2;
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,(g.*m2.*t7-g.*m2.*t9+L.*m2.*t2.*t6)./t13-m2.*t2.*t3.*t14.*u.*2.0-m2.*t2.*t3.*t14.*(L.*m2.*t3.*t6+g.*m2.*t2.*t3).*2.0,(1.0./(m1+m2-m2.*t7).^2.*(-g.*m1.^2.*t2+L.*t4.*t6+g.*t2.*t4-g.*t4.*t8+m1.*t3.*u+m2.*t3.*u-L.*t4.*t6.*t7-g.*m1.*m2.*t8+m2.*t3.*t7.*u+L.*m1.*m2.*t6-L.*m1.*m2.*t6.*t7.*2.0))./L,1.0,0.0,0.0,0.0,0.0,1.0,(L.*m2.*q2d.*t3.*2.0)./(m1+m2.*t9),(m2.*q2d.*sin(t5).*-2.0)./(m1.*2.0+m2-m2.*cos(t5))],[4,4]);
end
