% SANITY_BOUND  Null-model table: lunar tide vs. thrust authority per rung.
%
% Phase-1, no-solve script (runs in seconds). For each certified Table-3
% thrust rung (10, 5, 2.5, 1, 0.5, 0.2, 0.1 N) computes, purely from the
% existing 2-body campaign's certified lookup plus the CR3BP lunar-constant
% helper:
%   - thrust authority T/m0 [m/s^2]  (T_max over initial mass 1500 kg)
%   - lunar tidal acceleration at r = 1 LU (GEO radius), 2*muM*r/DM^3
%     converted to m/s^2 via kepler_lt_params' AU_ms2
%   - the tide/authority ratio [%]
%   - the rung's transfer duration t_f = 1.5*tfmin (campaign's c_tf), in
%     days and in lunar months (/27.32 d)
%
% This is the spec sec-7 "null hypothesis" table, computed FROM CODE (not
% copied from spec prose): the campaign's ladder walk (phase-1 steps 3-4)
% must beat this null model, or the deviation itself is the finding (spec
% sec 9 honesty rule -- if the loose asserts below fire, STOP and report;
% it means the null model is materially wrong, not a bug to silently fix).
%
% INPUTS:  none (script; iterates the certified rung set internally)
% OUTPUTS: none (prints an aligned table to stdout; writes
%          orbit_transfer/earth_elliptic_to_geo_CR3BP/direct/results/sanity_bound.md)
%
% REFERENCES:
%   [1] docs/superpowers/specs/2026-07-22-elliptic-geo-cr3bp-phase0-design.md
%       sec 7 (sanity bound / null hypothesis) and sec 9 (honesty rule).
%   [2] orbit_transfer/earth_elliptic_to_geo/direct/reproduce/table3_certified.m
%       (certified per-rung m_f, switches, revs, tfmin -- source of truth).
%   [3] orbit_transfer/earth_elliptic_to_geo_CR3BP/direct/lunar_params.m
%       (canonical lunar GM/distance/rate).
%   [4] Haberkorn, Martinon, Gergaud, "Low Thrust Minimum-Fuel Orbital
%       Transfer: A Homotopic Approach," JGCD 27(6), 2004, Table 3.

here = fileparts(mfilename('fullpath'));
addpath(here);
setup_paths;

rungsN    = [10, 5, 2.5, 1, 0.5, 0.2, 0.1];   % certified thrust rungs [N]
m0kg      = 1500;                              % initial mass [kg]
ispS      = 2000;                              % specific impulse [s]
c_tf      = 1.5;                                % campaign's t_f/t_fMin factor
monthDays = 27.32;                              % sidereal lunar month [days]

n            = numel(rungsN);
authority    = zeros(n,1);   % T/m0 [m/s^2]
tide         = zeros(n,1);   % lunar tidal accel at r=1 LU [m/s^2]
ratioPct     = zeros(n,1);   % tide/authority [%]
tfDays       = zeros(n,1);   % t_f [days]
tfMonths     = zeros(n,1);   % t_f [lunar months]

for k = 1:n
    thrustN = rungsN(k);
    par  = kepler_lt_params(thrustN, m0kg, ispS);
    pert = lunar_params(par, 0, 1);   % phi0=0, gain=1 (physical Moon)

    authority(k) = thrustN / m0kg;                              % [m/s^2]
    tide(k)      = 2*pert.muM*1/pert.DM^3 * par.AU_ms2;          % [m/s^2], r=1 LU
    ratioPct(k)  = 100 * tide(k) / authority(k);

    cert = table3_certified(thrustN);
    tfDays(k)   = c_tf * cert.tfmin * par.TU_s / 86400;
    tfMonths(k) = tfDays(k) / monthDays;
end

%% Print aligned table to stdout:
hdr = sprintf('%8s %14s %16s %12s %12s %14s', ...
    'T [N]', 'T/m0 [m/s2]', 'tide [m/s2]', 'ratio [%]', 't_f [days]', 't_f [months]');
sep = repmat('-', 1, numel(hdr));
fprintf('%s\n%s\n', hdr, sep);
for k = 1:n
    fprintf('%8.3g %14.4e %16.4e %12.4f %12.3f %14.4f\n', ...
        rungsN(k), authority(k), tide(k), ratioPct(k), tfDays(k), tfMonths(k));
end
fprintf('\n');

%% Loose-bracket asserts (spec sec 7 predictions; STOP + report if these fire):
idx10 = find(abs(rungsN - 10)  < 1e-9, 1);
idx01 = find(abs(rungsN - 0.1) < 1e-9, 1);
assert(ratioPct(idx10) >= 0.05 && ratioPct(idx10) <= 0.5, ...
    'sanity_bound:nullModel10N', ...
    '10 N tide/authority ratio %.4f%% outside [0.05%%, 0.5%%] -- spec sec 7 null model is materially wrong; STOP and report (sec 9).', ...
    ratioPct(idx10));
assert(ratioPct(idx01) >= 5 && ratioPct(idx01) <= 20, ...
    'sanity_bound:nullModel0p1N', ...
    '0.1 N tide/authority ratio %.4f%% outside [5%%, 20%%] -- spec sec 7 null model is materially wrong; STOP and report (sec 9).', ...
    ratioPct(idx01));
fprintf('sanity_bound: asserts PASS (10 N ratio = %.4f%%, 0.1 N ratio = %.4f%%)\n', ...
    ratioPct(idx10), ratioPct(idx01));

%% Write markdown table:
resultsDir = fullfile(here, 'results');
if ~exist(resultsDir, 'dir'), mkdir(resultsDir); end
mdFile = fullfile(resultsDir, 'sanity_bound.md');
fid = fopen(mdFile, 'w');
fprintf(fid, '# Sanity bound: lunar tide vs. thrust authority (null model)\n\n');
fprintf(fid, 'Generated by `sanity_bound.m` (phase1 T3). Source: certified\n');
fprintf(fid, '`table3_certified.m` rungs + `lunar_params.m` (spec sec 7).\n');
fprintf(fid, 'm0 = %g kg, Isp = %g s, c_tf = %g, lunar month = %g d.\n\n', ...
    m0kg, ispS, c_tf, monthDays);
fprintf(fid, '| T [N] | T/m0 [m/s^2] | lunar tide [m/s^2] | tide/authority [%%] | t_f [days] | t_f [lunar months] |\n');
fprintf(fid, '|---:|---:|---:|---:|---:|---:|\n');
for k = 1:n
    fprintf(fid, '| %g | %.4e | %.4e | %.4f | %.3f | %.4f |\n', ...
        rungsN(k), authority(k), tide(k), ratioPct(k), tfDays(k), tfMonths(k));
end
fprintf(fid, '\n**Asserts:** 10 N ratio in [0.05%%, 0.5%%] -- got %.4f%%. ', ratioPct(idx10));
fprintf(fid, '0.1 N ratio in [5%%, 20%%] -- got %.4f%%. Both PASS.\n', ratioPct(idx01));
fclose(fid);
fprintf('sanity_bound: wrote %s\n', mdFile);
