% RUN_VERIFY_1120  PMP-consistency certificate for the 1.12x direct solution.
setup_paths;
summary = verify_direct_pmp( ...
    '../sundman_minfuel/results/minfuel/legacy_ms_f1120.mat');
fprintf('run_verify_1120 done: worst state defect %.3e, matched %d/%d, primer %.4f deg, |lamM(end)| %.3e\n', ...
        summary.worstStateDef, summary.nMatched, summary.nSwitches, ...
        summary.primerMeanDeg, summary.lamMend);
