function cat_ = build_halo_catalog()
%% Purpose:
%
%   Packages the completed HALO -> TULIP sheets into the shareable compact
%   catalog costate_catalog_halo_tulip.mat, via the family-agnostic
%   packager costate_common/build_costate_catalog_family. Run from MATLAB
%   after the catalog run completes (run_halo_catalog('report') to check).
%
%% Inputs:
%
%   none
%
%% Outputs:
%
%  cat_                     struct                  The catalog, also saved
%                                                   to direct/results/
%                                                   costate_catalog_halo_tulip.mat
%
%% Revision History:
%  M. Casey                                                   (c) 08/07/2026
%  Copyright Coorbital Inc.
%% ------------------------ Begin Code Sequence ---------------------------

here = fileparts(mfilename('fullpath'));
addpath(fullfile(fileparts(here), 'costate_common'));

spec = struct( ...
  'glob', 'halo_tau*_Np*.mat', ...
  'name', 'costate_catalog_halo_tulip', ...
  'description', ['Minimum-time low-thrust HALO->Tulip costate CATALOG: ', ...
    'one phasing-torus sheet per (L2-southern halo period x tulip petal ', ...
    'count), thrust rungs walked 15->1 N. COMPACT format: canonical ND ', ...
    'quantities only; derived values reconstructed via .derive. Each entry ', ...
    'z8 = [lambda_r(3); lambda_v(3); lambda_m; tf] is a converged PMP ', ...
    'solution accepted unchanged by pumpkyn.cr3bp.tfMin. NOTE: ', ...
    'sheets(k).tauDRO is a LEGACY field name -- it holds the HALO period ', ...
    '(ND); sheets(k).dep_family/dep_params carry the full reconstruction ', ...
    'recipe (tau, Lpt, pm).'], ...
  'provenance', ['Halo catalog run (run_halo_catalog): per sheet, 6x6 ', ...
    'phasing torus anchored cold at 15 N and walked down; three gates per ', ...
    'entry (ms residual, flown arrival, tfMin acceptance). Departure: L2 ', ...
    'SOUTHERN halos (pm = -1); the northern branch is the exact z-mirror ', ...
    '(CR3BP symmetry), so mirror states and costates for pm = +1. Arrival ', ...
    'tulips pm = -1 branch, same mirror rule. Casey/Koblick 2026-08.'], ...
  'depReconstruction', ['halo: getHalo(dep_params.tau, dep_params.Lpt, ', ...
    'dep_params.pm)->cont_np->prop;  tulip: getTulip(2*pi*(Np-2)/(Np-1), ', ...
    'Np, pm)->cont_np->prop;  state at phase f: interp1(t, rv, ', ...
    'mod(f,1)*t(end), ''spline'')']);

catDir = fullfile(here, 'direct', 'results', 'catalog');
outMat = fullfile(here, 'direct', 'results', 'costate_catalog_halo_tulip.mat');
cat_ = build_costate_catalog_family(catDir, outMat, spec);
end
