% test_sosc_10N  Integration: full SOSC certificate on the 10 N MEE min-fuel row.
%
% FINAL direct reduced-Hessian method (DESIGN sec 12.1): sosc_inertia forms
% Z=null(full(A)) and RH=Z'HZ directly (no KKT eig, no sprank/Gould). The 10 N
% bang-bang min-fuel solution is a WEAK (non-strict) local minimum: the reduced
% Hessian is PSD (no negative curvature) with a large flat manifold (~270
% directions preserving the switching structure), and the negative count is
% threshold-STABLE across the zt-band. The certificate must return
% verdict=WEAK_MIN, status=certified-weak-min, red.nneg==0, sensStable==true,
% method=='reduced-eig', robust==true, nFlat within 3 of 270.
% This is a real IPOPT warm re-solve (~1-2 min).
root = fileparts(fileparts(mfilename('fullpath'))); cd(root); setup_paths;
addpath(fullfile(getenv('HOME'),'casadi-3.7.0'));
sosc = verify_sosc_mee(fullfile(module_root(),'results','MEE_M2_10N.mat'));
fprintf(['10 N verdict=%s reason="%s"\n  stat=%.2e drift=%.2e sign=%+d\n' ...
    '  primalEq=%.2e primalIneq=%.2e dualFeas=%.2e comp=%.2e\n' ...
    '  m_active=%d nEq=%d nStrong=%d nWeak=%d licq=%d\n' ...
    '  method=%s robust=%d rankA=%d sensStable=%d nnegBand=[%s]\n' ...
    '  reduced inertia red=[%d %d %d]  redMinEig=%.3e  nFlat=%d\n'], ...
    sosc.verdict, sosc.reason, sosc.kkt.stat, sosc.drift, sosc.sign, ...
    sosc.kkt.primalEq, sosc.kkt.primalIneq, sosc.kkt.dualFeas, sosc.kkt.comp, ...
    sosc.active.m_active, sosc.active.nEq, sosc.active.nStrong, sosc.active.nWeak, ...
    sosc.active.licq, sosc.method, sosc.robust, sosc.inertia.rankA, ...
    sosc.sensStable, num2str(sosc.nnegBand), ...
    sosc.red.npos, sosc.red.nneg, sosc.red.nzero, sosc.redMinEig, sosc.nFlat);

% Orchestrator correctness
assert(isfield(sosc,'verdict') && ischar(sosc.verdict), 'well-formed verdict');
assert(any(strcmp(sosc.verdict,{'PASS','WEAK_MIN','FAIL','INCONCLUSIVE','ERROR'})), 'verdict domain');
assert(strcmp(sosc.status, sosc_decide(sosc.kkt,sosc.active,sosc.inertia).status), ...
    'status consistent with sosc_decide');
assert(sosc.kkt.stat  < sosc.thresholds.stat,  'stationarity machine-tight');
assert(sosc.drift     < sosc.thresholds.drift, 'warm-resolve drift machine-tight');

% The payoff (FINAL-method acceptance gate): 10 N certifies as WEAK_MIN.
assert(strcmp(sosc.verdict,'WEAK_MIN'), ...
    '10 N expected WEAK_MIN, got %s (%s)', sosc.verdict, sosc.reason);
assert(strcmp(sosc.status,'certified-weak-min'), ...
    '10 N status expected certified-weak-min, got %s', sosc.status);
assert(sosc.red.nneg==0, '10 N reduced Hessian must have no negative curvature (red.nneg==0), got %d', sosc.red.nneg);
assert(sosc.sensStable==true, '10 N reduced negative count must be zt-stable (sensStable==true)');
assert(strcmp(sosc.method,'reduced-eig'), '10 N must use reduced-eig method, got %s', sosc.method);
assert(sosc.robust==true, '10 N inertia must be robust (n<=maxNullDim), got %d', sosc.robust);
assert(abs(sosc.nFlat-270)<=3, ...
    '10 N nFlat expected within 3 of 270 (true reduced-eig value), got %d', sosc.nFlat);

fprintf('test_sosc_10N PASSED: certified-weak-min, method=%s robust=%d nFlat=%d sensStable=%d\n', ...
    sosc.method, sosc.robust, sosc.nFlat, sosc.sensStable);
