function cat_ = build_minfuel_catalog()
% BUILD_MINFUEL_CATALOG  Package the min-fuel pilot records as the FIRST
% schema-v3 catalog: costate_catalog_dro_tulip_minfuel.mat.
%
% Sources: direct/results/minfuel_grid.mat (the eps-ladder record set),
% minfuel_rewalk_c25_g140.mat (the gamma-continuation replacement for the
% conj-refuted (2,5)@1.4 walk, if present), conj_fixedtf_verdicts.mat
% (fixed-tf Jacobi verdicts), and minenergy_pilot.mat (tf/tfMin, endpoints,
% thruster context). One sheet (DRO tau=1 -> tulip Np=7, the 12x12 phasing
% torus), axis3 = gamma [1.1 1.2 1.4]. Junction states (.Yj) ship for
% every entry per the identifiability rule; mf is STORED (coasts break the
% all-burn identity); conjugate verdicts + provenance ride inside.
%
% INPUTS:  none
% OUTPUTS: cat_ - the packaged catalog struct (also saved; schema-validated)
%
% REFERENCES:
%   [1] costate_common/catalog_schema.m (v3 field list; the validator).
%   [2] FINDINGS.md sections 18-20 (race, record set, conjugate verdicts).

here = fileparts(mfilename('fullpath'));
resDir = fullfile(here, 'direct', 'results');
addpath(fullfile(fileparts(here), 'costate_common'));
Lg = load(fullfile(resDir, 'minfuel_grid.mat'));
Lp = load(fullfile(resDir, 'minenergy_pilot.mat'));
Lv = load(fullfile(resDir, 'conj_fixedtf_verdicts.mat'));
G = Lg.G;

% Conjugate verdicts come ONLY from the fixed-tf sweep file (one record per
% kind/cell/gamma/source, each re-solved with keepSTMs and the spec echoed);
% the packager never trusts a verdict stored beside a solution (review
% 2026-09-05, P1.4).
vLook = @(src, cell, gam) Lv.V(find(arrayfun(@(v) strcmp(v.kind,'fuel') && ...
    strcmp(v.source, src) && isequal(v.cellIdx, cell) && abs(v.gamma-gam) < 1e-9, Lv.V), 1));

% swap in the gamma-continuation replacement for the refuted record, but
% only when BOTH (a) the sweep re-verdicted the rewalk solution PASS and
% (b) the original grid branch is refuted or worse in mass:
rwFile = fullfile(resDir, 'minfuel_rewalk_c25_g140.mat');
if isfile(rwFile)
    Lr = load(rwFile);
    vr = vLook('rewalk', Lr.R.cellIdx, Lr.R.gamma);
    kBad = find(arrayfun(@(g) isequal(g.cellIdx, Lr.R.cellIdx) && ...
                         abs(g.gamma - Lr.R.gamma) < 1e-9, G), 1);
    assert(~isempty(kBad), 'rewalk record (%d,%d)@%.2f has no grid counterpart', ...
           Lr.R.cellIdx, Lr.R.gamma);
    vg = vLook('grid', Lr.R.cellIdx, Lr.R.gamma);
    if ~isempty(vr) && vr.conjPass && ...
       (isempty(vg) || ~vg.conjPass || Lr.R.mfFuel > G(kBad).mfFuel)
        G(kBad).pDeepest = Lr.R.pDeepest;  G(kBad).mfFuel = Lr.R.mfFuel;
        G(kBad).z = Lr.R.z;  G(kBad).Y = Lr.R.Y;
        G(kBad).coastFrac = Lr.R.coastFrac;
        G(kBad).source = 'rewalk';
        fprintf('build_minfuel_catalog: (%d,%d)@%.2f replaced by gamma-continuation solution (sweep PASS, mf %.6f)\n', ...
                Lr.R.cellIdx, Lr.R.gamma, Lr.R.mfFuel);
    end
end

gammas = [1.1 1.2 1.4];
nD = 12;  nA = 12;  nG = numel(gammas);
rec1 = Lp.R(1);
K = size(G(1).Y, 2);
assert(all(arrayfun(@(g) size(g.Y, 2) == K, G)), 'mixed junction counts across records');
assert(all(arrayfun(@(r) abs(r.c - rec1.c) < 1e-12 && abs(r.Tmax - rec1.Tmax) < 1e-12, Lp.R)), ...
       'records do not share one propulsion set');

% Propulsion: DERIVE the labels from the physics actually flown (P0.1).
lStar = 389703.264829278;  tStar = 382981.289129055;  m0kg = 150;
ispS    = rec1.c * 1000 * lStar / (9.80665 * tStar);          % s
thrustN = rec1.Tmax * m0kg * lStar * 1000 / tStar^2;          % N
assert(abs(ispS - round(ispS)) < 1e-6, 'derived Isp %.6f s is not the torus value', ispS);
ispS = round(ispS);
assert(abs(thrustN - 0.07) < 1e-9, 'derived thrust %.9f N is not the torus value 0.07 N', thrustN);

sh = struct('tauDRO', 1.0, 'tau_dep', 1.0, ...
    'tau_arr', 2*pi*5/6, 'Np', 7, 'pm', -1, ...
    'dep_family', 'dro', 'dep_params', struct('tau', 1.0), ...
    'arr_family', 'tulip', 'arr_params', struct('Np', 7, 'pm', -1), ...
    'period_tulip_nd', 2*pi*5/6, ...
    'sD_frac', (0:nD-1)/nD, 'sA_frac', 0.075378 + (0:nA-1)/nA, ...
    'has_solution', false(nD, nA, nG), 'tf_nd', nan(nD, nA, nG), ...
    'entry_index', zeros(nD, nA, nG), 'tfmin_nd', nan(nD, nA), ...
    'p_floor', nan(nD, nA, nG), 'mf_frac', nan(nD, nA, nG), ...
    'conj_pass', -ones(nD, nA, nG, 'int8'), ...
    'lam0', zeros(7, 0), 'Yj', zeros(14, K+1, 0));

for k = 1:numel(G)
    g = G(k);
    iD = g.cellIdx(1);  iA = g.cellIdx(2);
    kg = find(abs(gammas - g.gamma) < 1e-9);
    rec = Lp.R(find(arrayfun(@(r) isequal([r.iD r.iA], g.cellIdx) && ...
                             abs(r.gam - g.gamma) < 1e-9, Lp.R), 1));
    sh.has_solution(iD, iA, kg) = true;
    sh.tf_nd(iD, iA, kg) = rec.tf;
    sh.tfmin_nd(iD, iA) = rec.tf/g.gamma;
    sh.p_floor(iD, iA, kg) = g.pDeepest;
    sh.mf_frac(iD, iA, kg) = g.mfFuel;
    sh.lam0(:, end+1) = g.z;
    % terminal junction column: propagate the last stored segment
    sm = struct('family', 'eps', 'p', g.pDeepest);
    yT = cr3bp_minfuel_prop(rec.tf/K, g.Y(:,end), false, ...
                            rec.Tmax, rec.c, rec.muStar, sm);
    sh.Yj(:, :, size(sh.lam0, 2)) = [g.Y, yT];
    sh.entry_index(iD, iA, kg) = size(sh.lam0, 2);
    % conjugate verdict from the sweep, bound to the packaged branch by
    % source AND by the initial costate (the verdict must have been
    % computed on the very solution being shipped):
    src = 'grid';
    if isfield(g, 'source') && ~isempty(g.source), src = g.source; end
    v = vLook(src, g.cellIdx, g.gamma);
    assert(~isempty(v), 'no %s conjugate verdict for (%d,%d)@%.2f', src, g.cellIdx, g.gamma);
    assert(norm(v.z - g.z) < 1e-8 * max(1, norm(g.z)), ...
           '%s verdict for (%d,%d)@%.2f was computed on a different solution (|dz| = %.1e)', ...
           src, g.cellIdx, g.gamma, norm(v.z - g.z));
    assert(isequal(v.stateRows, 1:7), 'verdict for (%d,%d)@%.2f used rows %s, need 1:7', ...
           g.cellIdx, g.gamma, mat2str(v.stateRows));
    assert(v.converged, '%s verdict for (%d,%d)@%.2f is from an UNCONVERGED re-solve', src, g.cellIdx, g.gamma);
    assert(abs(v.p - g.pDeepest) < 1e-12, '%s verdict for (%d,%d)@%.2f at p=%.6g, entry at p=%.6g', ...
           src, g.cellIdx, g.gamma, v.p, g.pDeepest);
    assert(isfield(v, 'tested') && v.tested, '%s verdict for (%d,%d)@%.2f is UNDETERMINED (nothing testable)', ...
           src, g.cellIdx, g.gamma);
    sh.conj_pass(iD, iA, kg) = int8(v.conjPass);
end
assert(all(sh.conj_pass(sh.has_solution) >= 0), 'an entry is missing its conjugate verdict');

cat_ = struct( ...
    'name', 'costate_catalog_dro_tulip_minfuel', ...
    'description', ['FIRST schema-v3 (objective/gamma axis) catalog: fixed-tf ' ...
        'MIN-FUEL entries, DRO(tau=1) -> tulip(Np=7) 12x12 phasing torus, ' ...
        'gamma = tf/tfMin in {1.1,1.2,1.4}, Bertrand-Epenoy eps ladder walked ' ...
        'to the stored p_floor (~0.001-0.005). mf is STORED (coast arcs break ' ...
        'the all-burn identity); dV via derive deltav_from_mf. Yj = full ms ' ...
        'junction states per entry (identifiability rule). conj_pass = ' ...
        'fixed-tf Jacobi verdicts (FINDINGS 20); the (2,5)@1.4 entry is the ' ...
        'gamma-continuation replacement for a conj-refuted eps-walk branch.'], ...
    'schema', 3, 'objective', 'minfuel', ...
    'axis3', struct('name', 'gamma', 'values', gammas), ...
    'smoothing', struct('family', 'eps', 'note', ...
        ['throttle law s* = clip((Q-(1-eps))/(2eps),0,1), Q = T(|lam_v|/m + ' ...
         'lam_m/c); entries solved at eps = p_floor, NOT eps = 0 (the exact ' ...
         'bang-bang limit is nonsmooth); mf converged to ~1e-5 by eps 0.005']), ...
    'created', char(datetime('today', 'Format', 'yyyy-MM-dd')), ...
    'provenance', 'run_minfuel_grid + run_minfuel_race (eps arm) + rewalk (FINDINGS 18-20)', ...
    'constants', struct('muStar', rec1.muStar, 'lStar_km', lStar, ...
                        'tStar_s', tStar), ...
    'thruster', struct('isp_s', ispS, 'm0_kg', m0kg, 'thrustN', thrustN, ...
                       'c_nd', rec1.c, 'Tmax_nd', rec1.Tmax, ...
                       'note', ['isp_s and thrustN DERIVED from the record''s c_nd/Tmax_nd ' ...
                                '(the 12x12 torus substrate: 0.07 N, Isp 900 s, 150 kg) -- ' ...
                                'review 2026-09-05 P0.1: an earlier build hardcoded 1710 s']), ...
    'sheets', sh, 'n_entries', size(sh.lam0, 2), ...
    'env', struct('matlab', version, 'built', char(datetime)), ...
    'derive', struct( ...
        'days_from_nd', 't_days = t_nd * constants.tStar_s/86400', ...
        'tf', 'tf_nd = gamma * sheets(k).tfmin_nd(iD,iA)', ...
        'deltav_kms', 'catalog_schema derive deltav_from_mf on the STORED mf_frac', ...
        'reconstruction', ['fly cr3bp_minfuel_prop from Yj(:,1,n) over tf at ' ...
                           'smoothing (family, p_floor) -- or reconverge ' ...
                           'ms_minfuel from the Yj junctions']), ...
    'conj_test', struct('kind', ['fixed-tf Jacobi (ms_conjugate_test spec: no flow column, no quotient, ' ...
                                 'rows 1:7 = full state, cols 8:14; initial-coast structural zeros ' ...
                                 'skipped; final segment sampled)'], ...
                        'validated', 'tests/test_conj_fixedtf (analytic LQ pi case + coast/final-segment fixtures)', ...
                        'sweep', 'run_conj_fixedtf_sweep -> conj_fixedtf_verdicts.mat (verdict bound to lam0)', ...
                        'date', char(datetime('today', 'Format', 'yyyy-MM-dd'))));

pb = catalog_schema('validate', cat_);
assert(isempty(pb), 'v3 validation failed: %s', strjoin(pb, '; '));
outMat = fullfile(resDir, 'costate_catalog_dro_tulip_minfuel.mat');
costate_catalog_dro_tulip_minfuel = cat_; %#ok<NASGU>
save(outMat, 'costate_catalog_dro_tulip_minfuel');
fprintf('%s: %d entries, schema v3 clean -> %s\n', cat_.name, cat_.n_entries, outMat);
end
