% PROBE_SCALED_LM  Diagnostic: same Branch-A eps=1/M=48 solve but with
% Marquardt Jacobian scaling (ScaleProblem='jacobian'). Tests whether the
% slow-valley LM behavior is a scaling artifact (costate rows ~2e2 vs state
% rows ~1). Does NOT modify ms_solve.m; local lsqnonlin call only.
setup_paths;
M = 48;
matFile = '/Users/msc/Desktop/optimal_control/NLP_lowThrust_GTO_tulip/sundman_minfuel/results/minfuel/legacy_ms_f1120.mat';
[Zseed, tJ, info] = seed_from_duals(matFile, 1.12, M);
fprintf('beta=%.4g spread=%.1f%% burnAgree=%.1f%% arcCheckErr=%.2e\n', ...
        info.beta, info.spreadPct, 100*info.burnAgree, info.arcCheckErr);
prob    = ms_problem(1.12, 1);
prob.tJ = tJ;
opts = optimoptions('lsqnonlin', ...
    'Display', 'iter', ...
    'Algorithm', 'levenberg-marquardt', ...
    'ScaleProblem', 'jacobian', ...
    'SpecifyObjectiveGradient', true, ...
    'FunctionTolerance', 1e-24, ...
    'StepTolerance', 1e-14, ...
    'MaxIterations', 300, ...
    'MaxFunctionEvaluations', 6000);
tA = tic;
[Z, res2, ~, flag, outp] = lsqnonlin(@(zz) ms_residual(zz, prob), Zseed(:), [], [], opts);
fprintf('PROBE_SCALED: ||R||=%.3e iters=%d flag=%d wall=%.1fs\n', ...
        sqrt(res2), outp.iterations, flag, toc(tA));
save('probe_scaled_result.mat', 'Z', 'res2', 'flag');
